[package]
name = "turtle_wa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
http = "0.2.8"

[dev-dependencies]
pretty_assertions = "1.3.0"